### ISSUE TITLE
Ability to download paid posts too

### ISSUE THREAD

**Issue by yourkidelias** [alexferrari88/sbstck-dl#1]
Hi,
Is there any possibility to include the option to download posts behind a pay-wall? Let me explain myself, I have paid for access to a private substack and I would like to download the posts for offline use and would love if the program could authenticate itself using my account and then download all the posts just as it would do if they were public instead of private.

**Comment by alexferrari88** [comment]
hi, this is in the roadmap but unfortunately I have no way to develop this since I don't pay for any Substack newsletter so I won't be able to test it. I'd be happy to accept any PR implementing this (granting it's a valid one)

**Comment by yourkidelias** [comment]
Hi Alex,
Thanks for the reply but I solved it by building a new app that uses Puppetter to use the user's browser in order to download all posts from a paid Substack newsletter. It does not work as smooth as yours as it shows the browser doing all the dirty work but it completed the goal so I am happy
[download-paid-substacks](https://github.com/yourkidelias/download-paid-substacks)
